package cc.rinoux.server.model;

public class Cup {

    private Integer cupId;
    private String mac;
    private String ip;
    private String memoryStatus;
    public Integer getCupId() {
        return cupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup.cup_id
     *
     * @param cupId the value for cup.cup_id
     *
     * @mbggenerated
     */
    public void setCupId(Integer cupId) {
        this.cupId = cupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cup.mac
     *
     * @return the value of cup.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup.mac
     *
     * @param mac the value for cup.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cup.ip
     *
     * @return the value of cup.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup.ip
     *
     * @param ip the value for cup.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cup.memory_status
     *
     * @return the value of cup.memory_status
     *
     * @mbggenerated
     */
    public String getMemoryStatus() {
        return memoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup.memory_status
     *
     * @param memoryStatus the value for cup.memory_status
     *
     * @mbggenerated
     */
    public void setMemoryStatus(String memoryStatus) {
        this.memoryStatus = memoryStatus;
    }


	public Cup(String mac, String ip, String memoryStatus) {
		super();
		this.mac = mac;
		this.ip = ip;
		this.memoryStatus = memoryStatus;
	}

	public Cup() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	@Override
	public String toString(){
		return "[cup info||"+"cupID=" + cupId +",IP=" + ip + ",status=" + memoryStatus + "]";
	}
    
    
}