package cc.rinoux.server.model;

public class CupImages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cup_images.cup_id
     *
     * @mbggenerated
     */
    private Integer cupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cup_images.img_id
     *
     * @mbggenerated
     */
    private Integer imgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cup_images.cup_id
     *
     * @return the value of cup_images.cup_id
     *
     * @mbggenerated
     */
    public Integer getCupId() {
        return cupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup_images.cup_id
     *
     * @param cupId the value for cup_images.cup_id
     *
     * @mbggenerated
     */
    public void setCupId(Integer cupId) {
        this.cupId = cupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cup_images.img_id
     *
     * @return the value of cup_images.img_id
     *
     * @mbggenerated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cup_images.img_id
     *
     * @param imgId the value for cup_images.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

	public CupImages(Integer cupId, Integer imgId) {
		super();
		this.cupId = cupId;
		this.imgId = imgId;
	}
    
    
}