package cc.rinoux.server.model;

public class Image {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.img_id
     *
     * @mbggenerated
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.u_id
     *
     * @mbggenerated
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.img_name
     *
     * @mbggenerated
     */
    private String imgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.thumbnail
     *
     * @mbggenerated
     */
    private String thumbnail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.img_id
     *
     * @return the value of image.img_id
     *
     * @mbggenerated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.img_id
     *
     * @param imgId the value for image.img_id
     *
     * @mbggenerated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.u_id
     *
     * @return the value of image.u_id
     *
     * @mbggenerated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.u_id
     *
     * @param uId the value for image.u_id
     *
     * @mbggenerated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.url
     *
     * @return the value of image.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.url
     *
     * @param url the value for image.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.img_name
     *
     * @return the value of image.img_name
     *
     * @mbggenerated
     */
    public String getImgName() {
        return imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.img_name
     *
     * @param imgName the value for image.img_name
     *
     * @mbggenerated
     */
    public void setImgName(String imgName) {
        this.imgName = imgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.thumbnail
     *
     * @return the value of image.thumbnail
     *
     * @mbggenerated
     */
    public String getThumbnail() {
        return thumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.thumbnail
     *
     * @param thumbnail the value for image.thumbnail
     *
     * @mbggenerated
     */
    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    
    /*
	public Image(Integer uId, String url, String imgName, String thumbnail) {
		super();
		this.uId = uId;
		this.url = url;
		this.imgName = imgName;
		this.thumbnail = thumbnail;
	}
	*/
    
    
    
}