package cc.rinoux.server.model;

import java.util.Date;

public class Note {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.note_id
     *
     * @mbggenerated
     */
    private Integer noteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.alert_date
     *
     * @mbggenerated
     */
    private Date alertDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.note_id
     *
     * @return the value of note.note_id
     *
     * @mbggenerated
     */
    public Integer getNoteId() {
        return noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.note_id
     *
     * @param noteId the value for note.note_id
     *
     * @mbggenerated
     */
    public void setNoteId(Integer noteId) {
        this.noteId = noteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.content
     *
     * @return the value of note.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.content
     *
     * @param content the value for note.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.alert_date
     *
     * @return the value of note.alert_date
     *
     * @mbggenerated
     */
    public Date getAlertDate() {
        return alertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.alert_date
     *
     * @param alertDate the value for note.alert_date
     *
     * @mbggenerated
     */
    public void setAlertDate(Date alertDate) {
        this.alertDate = alertDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.image
     *
     * @return the value of note.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.image
     *
     * @param image the value for note.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image;
    }
}