package cc.rinoux.server.mapper;

import cc.rinoux.server.model.CupImages;

public interface CupImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    int insert(CupImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    int insertSelective(CupImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    CupImages selectByPrimaryKey(Integer cupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CupImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cup_images
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CupImages record);
}