package cc.rinoux.server.mapper;

import cc.rinoux.server.model.Cup;

public interface CupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	int insert(Cup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	int insertSelective(Cup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	Cup selectByPrimaryKey(Integer cid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Cup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cup
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Cup record);
}